Entities refactor
Mickss/champmaker pull request #17
Opened 2023-05-04 18:26 UTC by Mickss

2023-05-04 19:07 UTC, kbnowak approved these changes
Please fix the empty line before merging

2023-05-04 19:07 UTC, kbnowak commented on src/main/java/org/micks/champmaker/players/PlayerEntity.java
> -
should this empty line stay?

2023-05-05 05:22 UTC, tknowak requested changes
Application does not compile anymore.

2023-05-05 18:28 UTC, tknowak approved these changes

2023-05-05 18:31 UTC, merged