Get teams signed up for the tournament
Mickss/champmaker pull request #6
Opened 2022-09-14 07:44 UTC by Mickss

2022-09-14 07:48 UTC, tknowak approved these changes
Good job 🙂

2022-09-14 11:07 UTC, kbnowak requested changes

2022-09-14 11:07 UTC, kbnowak commented on src/main/java/org/micks/champmaker/register/RegisterService.java
> +                .map(RegisterEntity::getTeamId).collect(Collectors.toList());
static import please

2022-09-16 06:03 UTC, tknowak approved these changes

2022-09-16 07:09 UTC, merged